model:
  best_model: XGBoost
  mae: 2456.779771898088
  name: insurance_price_model
  parameters:
    objective: reg:squarederror
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: null
    device: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: null
    feature_types: null
    feature_weights: null
    gamma: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.05
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 3
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    multi_strategy: null
    n_estimators: 100
    n_jobs: null
    num_parallel_tree: null
    random_state: null
    reg_alpha: null
    reg_lambda: null
    sampling_method: null
    scale_pos_weight: null
    subsample: null
    tree_method: null
    validate_parameters: null
    verbosity: null
  r2_score: 0.9007822359147879
  target_variable: charges
